/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "Person.h"
/* Header for class com_maxst_www_ndkpractice_NativeManager */

#ifndef _Included_com_maxst_www_ndkpractice_NativeManager
#define _Included_com_maxst_www_ndkpractice_NativeManager
#ifdef __cplusplus

#include <android/log.h>
extern "C" {
#endif
/*
 * Class:     com_maxst_www_ndkpractice_NativeManager
 * Method:    getSomething
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_maxst_www_ndkpractice_NativeManager_getSomething
        (JNIEnv *env, jobject) {
    return env->NewStringUTF("Hello World");
}

JNIEXPORT jstring JNICALL Java_com_maxst_www_ndkpractice_NativeManager_getSomething2
        (JNIEnv *env, jobject) {
    __android_log_write(ANDROID_LOG_ERROR, "Test", "Charles");
    return env->NewStringUTF(Person().say());
}

#ifdef __cplusplus
}
#endif
#endif
